### ISSUE TITLE
Support newer versions of ecto_sql 

### ISSUE THREAD

**Issue by elephantoss** [Flagsmith/flagsmith-elixir-client#23]
Latest ecto version is 3.10 and because the ecto dependency in the lib is defined as `~> 3.7` it means it cannot use the newer versions of ecto_sql

**Comment by khvn26** [comment]
Hello and thanks for reporting! Would you like to open a PR for this?

**Comment by elephantoss** [comment]
I'm testing the fix and I'll open a PR once I'm done
