### ISSUE TITLE
How to identify users?

### ISSUE THREAD

**Issue by elephantoss** [Flagsmith/flagsmith-elixir-client#31]
I'm trying to identify and add traits to users but I don't find a way to do that with the elixir client.

What would be the recommended way to achieve that?

**Comment by dabeeeenster** [comment]
As per the [docs](https://docs.flagsmith.com/clients/server-side#get-flags-for-an-identity):

```elixir
# The method below triggers a network request
{:ok, flags} = Flagsmith.Client.get_identity_flags(
      client_configuration,
      "user-a",
      [%{trait_key: "is_subscribed", trait_value: false}]
)

secret_button_enabled? = Flagsmith.Client.is_feature_enabled(flags, "secret_button")
secret_button_feature_value = Flagsmith.Client.get_feature_value(flags, "secret_butteon")
```

**Comment by elephantoss** [comment]
@dabeeeenster `Flagsmith.Client.get_identity_flags`  get the flags and also updates traits for the given user?

If that's the case, wouldn't be better to have a function to only updates traits for cases when users are not evaluating flags?

Eg: during login I want to update traits for the user that is logging into the application, but I don't want to get any flags, as I'm not evaluating anything

**Comment by dabeeeenster** [comment]
Ah understood. I will get the following added to the docs:

```
- By default, all Traits defined in the SDK will automatically be persisted against the Identity within the Flagsmith API.
- Traits passed to the SDK will be added to all the other Traits associated with that Identity.
- This full set of Traits are then used to evaluate the Flag values for the Identity.
- This all happens in a single request/response.
```

I don't really understand why you would want to set traits but not receive Flags at the same time? Given the new traits may modify the associated flag values?

**Comment by elephantoss** [comment]
@dabeeeenster The use case I had in mind is when the system is running some background jobs and traits change. Since there is no user interaction and flag evaluation at the time, just updating the traits would suffice.

Another case, the user is logging into the application, but I'm not evaluating any flags, and I'll call `is_feature_enable` just later after the user gets redirected to some page inside the application.

In both cases, the returned flags will be ignored.

**Comment by dabeeeenster** [comment]
I think in that case just ignore everything other than the 200 response.
